export const SET_LOGIN_STAUTS = "LOGIN/SET_LOGIN_STAUTS";
export const SET_USERDATA = "LOGIN/SET_USERDATA";
export const SET_IS_CHECK_LOGIN = "LOGIN/SET_IS_CHECK_LOGIN";
export const SET_SIGNUP_USER_NAME = "LOGIN/SET_SIGNUP_USER_NAME";
export const CLEAN_UP = "LOGIN/CLEAN_UP";
